import { FormEvent, useEffect, useState } from 'react';
import { api, mensajeDeError } from '../api/client';
import { Encabezado } from '../components/Encabezado';
import { pesos } from '../utils/formato';
interface Clase { grupoMateriaId: number; grupo: string; materia: string; plantel: string; inscritos: number; oficialesCompletos: number; promedioOficial: number | null; aprobados: number; bajoReferencia: number; entregasEsperadas: number; entregasRecibidas: number; entregasFaltantes: number; parciales: { parcial: number; capturados: number; faltantes: number; promedio: number | null }[] }
interface Resultado { ciclo: { nombre: string }; generadoEn: string; academico?: { regla: string; clases: Clase[] }; financiero?: { cargos: number; facturado: number; aplicado: number; saldo: number } }
export default function AnaliticaPage() {
  const [ciclos, setCiclos] = useState<{ id: number; clave: string }[]>([]); const [planteles, setPlanteles] = useState<{ id: number; nombre: string }[]>([]);
  const [cicloId, setCicloId] = useState(''); const [plantelId, setPlantelId] = useState(''); const [datos, setDatos] = useState<Resultado | null>(null); const [error, setError] = useState(''); const [cargando, setCargando] = useState(false);
  useEffect(() => { Promise.all([api.get('/academico/ciclos'), api.get('/planteles/mios')]).then(([c, p]) => { setCiclos(c.data); setPlanteles(p.data); }).catch((err) => setError(mensajeDeError(err))); }, []);
  const consultar = async (e: FormEvent) => { e.preventDefault(); if (cargando) return; setCargando(true); setError(''); setDatos(null); try { const { data } = await api.get<Resultado>('/analitica', { params: { ...(cicloId ? { cicloId } : {}), ...(plantelId ? { plantelId } : {}) } }); setDatos(data); } catch (err) { setError(mensajeDeError(err)); } finally { setCargando(false); } };
  return <><Encabezado titulo="Analítica académica y financiera" detalle="Indicadores por ciclo, plantel y clase, limitados a tus permisos." />
    <form onSubmit={consultar} className="fila"><div className="campo"><label htmlFor="ciclo-analitica">Ciclo</label><select id="ciclo-analitica" value={cicloId} onChange={(e) => setCicloId(e.target.value)}><option value="">Vigente</option>{ciclos.map((c) => <option key={c.id} value={c.id}>{c.clave}</option>)}</select></div><div className="campo"><label htmlFor="plantel-analitica">Plantel</label><select id="plantel-analitica" value={plantelId} onChange={(e) => setPlantelId(e.target.value)}><option value="">Todos los permitidos</option>{planteles.map((p) => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></div><button className="boton" disabled={cargando}>{cargando ? 'Consultando…' : 'Consultar indicadores'}</button></form>
    {error && <p role="alert" className="mensaje-error">{error}</p>}{datos && <><p role="status">{datos.ciclo.nombre} · Actualizado: {new Date(datos.generadoEn).toLocaleString('es-MX')}</p>
      {datos.financiero && <section className="panel"><h2>Finanzas del ciclo</h2><dl><dt>Cargos vigentes</dt><dd>{datos.financiero.cargos}</dd><dt>Facturado después de descuentos y recargos</dt><dd>{pesos(datos.financiero.facturado)}</dd><dt>Pagos aplicados</dt><dd>{pesos(datos.financiero.aplicado)}</dd><dt>Saldo</dt><dd>{pesos(datos.financiero.saldo)}</dd></dl></section>}
      {datos.academico && <section className="panel"><h2>Seguimiento por clase</h2><p>{datos.academico.regla}</p><table className="tabla"><thead><tr><th>Plantel / Grupo / Materia</th><th>Inscritos</th><th>Captura P1 / P2 / P3</th><th>Promedio oficial</th><th>Completos</th><th>Aprobados / bajo referencia</th><th>Entregas vencidas</th></tr></thead><tbody>{datos.academico.clases.map((c) => <tr key={c.grupoMateriaId}><td>{c.plantel} · {c.grupo} · {c.materia}</td><td>{c.inscritos}</td><td>{c.parciales.map((p) => `P${p.parcial}: ${p.capturados} capturados, ${p.faltantes} faltantes`).join(' / ')}</td><td>{c.promedioOficial ?? 'Pendiente'}</td><td>{c.oficialesCompletos}</td><td>{c.aprobados} / {c.bajoReferencia}</td><td>{c.entregasRecibidas} de {c.entregasEsperadas}; faltan {c.entregasFaltantes}</td></tr>)}</tbody></table>{!datos.academico.clases.length && <p>Sin clases dentro del alcance seleccionado.</p>}</section>}
    </>}</>;
}
